-- This file has been generated by Dungeon Editor 2.2.4

-- TODO: place your custom sound definitions here
defineSound{
	name = "assassination",
	filename = "mod_assets/sounds/LevelUp.wav",
	loop = false,
	volume = 1,
	minDistance = 1,
	maxDistance = 5,
}

defineSound{
	name = "monk_light",
	filename = "mod_assets/sounds/monk_light.wav",
	loop = false,
	volume = 1,
	minDistance = 1,
	maxDistance = 5,
}

defineSound{
	name = "tinker",
	filename = "mod_assets/sounds/tinker.wav",
	loop = false,
	volume = 1,
	minDistance = 1,
	maxDistance = 5,
}

defineSound{
	name = "time_1",
	filename = "mod_assets/sounds/Time_1.wav",
	loop = false,
	volume = 1,
	minDistance = 1,
	maxDistance = 5,
}

defineSound{
	name = "time_2",
	filename = "mod_assets/sounds/Time_2.wav",
	loop = false,
	volume = 1,
	minDistance = 1,
	maxDistance = 5,
}

defineSound{
	name = "sx_waterfall",
	filename = "mod_assets/sounds/sx_waterfall.wav",
	loop = true,
	volume = 10.00,
	minDistance = 0,
	maxDistance = 8,
}

defineSound{
	name = "monster_cast",
	filename = "mod_assets/sounds/monster_cast.wav",
	loop = false,
	volume = 1,
	minDistance = 1,
	maxDistance = 10,
}