-- This file has been generated by Dungeon Editor 2.2.4

-- TODO: place your custom tile definitions here
defineTile{
	name = "beach_wall",
	editorIcon = 196,
	color = {115,100,70,255},
	solid = true,
	builder = "mine",
	wall = {
		"beach_rock_wall_01", 1,
		"beach_rock_wall_02", 1,	
		"beach_rock_wall_04", 1,
	},
	centerPillar = {
		"beach_rock_pillar_01", 1,
	},
	-- floor geometry is generated by heightmap
	heightmapMaterial = "beach_ground_01",
	automapTile = "rocky_wall",
}