-- concentration ---------------------------------------------------------------

defineParticleSystem{
  name = "arcane_bolt",
  emitters = {
    {
      emissionRate = 256,
      emissionTime = 0,
      maxParticles = 32,
      sprayAngle = {0,360},
      velocity = {0,1},
      objectSpace = false,
      texture = "assets/textures/particles/glitter_silver.tga",
      lifetime = {0.5,1},
      color0 = {3,1,1},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.1,
      size = {0.05, 0.5},
      gravity = {0,0,0},
      airResistance = 5,
      rotationSpeed = 5,
      blendMode = "Additive",
    },
    {
      emissionRate = 256,
      emissionTime = 0,
      maxParticles = 32,
      sprayAngle = {0,360},
      velocity = {0,1},
      objectSpace = false,
      texture = "assets/textures/particles/glitter_silver.tga",
      lifetime = {0.5,1},
      color0 = {1,1,3},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.1,
      size = {0.05, 0.5},
      gravity = {0,0,0},
      airResistance = 5,
      rotationSpeed = 5,
      blendMode = "Additive",
    },
    {
      spawnBurst = true,
      maxParticles = 1,
      sprayAngle = {0,0},
      velocity = {0,0},
      objectSpace = true,
      texture = "assets/textures/particles/glow.tga",
      lifetime = {1000000,1000000},
      color0 = {0.25,0.2,0.25},
      opacity = 1,
      fadeIn = 0.001,
      fadeOut = 0.001,
      size = {0.5, 0.5},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 0,
      blendMode = "Additive",
    },
  }
}

defineParticleSystem{
  name = "arcane_blast",
  emitters = {
    {
      spawnBurst = true,
      maxParticles = 128,
      sprayAngle = {0,360},
      velocity = {2,5},
      objectSpace = false,
      texture = "assets/textures/particles/glitter_silver.tga",
      lifetime = {0.6,1},
      color0 = {3.0,3.0,3.0},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.5,
      size = {0.04, 0.2},
      gravity = {0,0,0},
      airResistance = 4,
      rotationSpeed = 2,
      blendMode = "Additive",
    },
    {
      spawnBurst = true,
      maxParticles = 128,
      sprayAngle = {0,360},
      velocity = {2,5},
      objectSpace = false,
      texture = "assets/textures/particles/glitter_silver.tga",
      lifetime = {0.6,1},
      color0 = {3.0,1.8,3.0},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.5,
      size = {0.04, 0.2},
      gravity = {0,0,0},
      airResistance = 4,
      rotationSpeed = -2,
      blendMode = "Additive",
    },
    {
      spawnBurst = true,
      maxParticles = 1,
      sprayAngle = {0,0},
      velocity = {0,0},
      objectSpace = false,
      texture = "assets/textures/particles/glow.tga",
      lifetime = {1,1},
      color0 = {1.0,0.6,1.0},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.9,
      size = {1.8, 1.8},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 0,
      blendMode = "Additive",
    },
  }
}

defineParticleSystem{
  name = "arcane_flash_blast",
  emitters = {
    {
      spawnBurst = true,
      maxParticles = 512,
      sprayAngle = {0,360},
      velocity = {512,512},
      objectSpace = false,
      texture = "assets/textures/particles/glitter_silver.tga",
      lifetime = {0.6,1},
      color0 = {3.0,3.0,3.0},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.5,
      size = {0.04, 0.2},
      gravity = {0,0,0},
      airResistance = 512,
      rotationSpeed = 2,
      blendMode = "Additive",
    },
    {
      spawnBurst = true,
      maxParticles = 1,
      sprayAngle = {0,360},
      velocity = {0,0},
      objectSpace = false,
      texture = "assets/textures/particles/glow.tga",
      lifetime = {1,1},
      color0 = {1.0,1.0,1.0},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.9,
      size = {3, 3},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 0,
      blendMode = "Additive",
    },
    {
      spawnBurst = true,
      maxParticles = 1,
      sprayAngle = {0,360},
      velocity = {0,0},
      objectSpace = false,
      texture = "assets/textures/lensflare/streaks.tga",
      lifetime = {1,1},
      color0 = {1.0,1.0,1.0},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.9,
      size = {3, 3},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 4,
      blendMode = "Additive",
    },
  }
}

defineParticleSystem{
  name = "arcane_nova_blast",
  emitters = {
    {
      spawnBurst = true,
      maxParticles = 256,
      sprayAngle = {0,360},
      velocity = {2,8},
      objectSpace = false,
      texture = "assets/textures/particles/glitter_silver.tga",
      lifetime = {0.6,1},
      color0 = {3.0,3.0,3.0},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.5,
      size = {0.04, 0.2},
      gravity = {0,0,0},
      airResistance = 4,
      rotationSpeed = 2,
      blendMode = "Additive",
    },
    {
      spawnBurst = true,
      maxParticles = 256,
      sprayAngle = {0,360},
      velocity = {2,8},
      objectSpace = false,
      texture = "assets/textures/particles/glitter_silver.tga",
      lifetime = {0.6,1},
      color0 = {3.0,1.8,3.0},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.5,
      size = {0.04, 0.2},
      gravity = {0,0,0},
      airResistance = 4,
      rotationSpeed = -2,
      blendMode = "Additive",
    },
    {
      spawnBurst = true,
      maxParticles = 1,
      sprayAngle = {0,0},
      velocity = {0,0},
      objectSpace = false,
      texture = "assets/textures/particles/glow.tga",
      lifetime = {1,1},
      color0 = {1.0,0.6,1.0},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.9,
      size = {3.2, 3.2},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 0,
      blendMode = "Additive",
    },
  }
}

defineParticleSystem{
  name = "arcane_flash_bolt",
  emitters = {
    {
      spawnBurst = true,
      maxParticles = 1,
      boxMin = {0,0,0},
      boxMax = {0,0,0},
      sprayAngle = {0,360},
      velocity = {0,0},
      texture = path.."textures/particles/lightning_ball.tga",
      lifetime = {1000000, 1000000},
      colorAnimation = false,
      color0 = {1,1,1},
      opacity = 0.5,
      size = {1,1},
      gravity = {0,0,0},
      airResistance = 5,
      rotationSpeed = 7,
      blendMode = "Additive",
      objectSpace = true,
    },
    {
      spawnBurst = true,
      maxParticles = 1,
      boxMin = {0,0,0},
      boxMax = {0,0,0},
      sprayAngle = {0,360},
      velocity = {0,0},
      texture = path.."textures/particles/lightning_ball.tga",
      lifetime = {1000000, 1000000},
      colorAnimation = false,
      color0 = {1,1,1},
      opacity = 0.5,
      size = {1,1},
      gravity = {0,0,0},
      airResistance = 5,
      rotationSpeed = -7,
      blendMode = "Additive",
      objectSpace = true,
    },
--spray
    {
      emissionRate = 500,
      emissionTime = 0,
      maxParticles = 1000,
      boxMin = {0,0,0},
      boxMax = {0,0,0},
      objectSpace = false,
      sprayAngle = {0,360},
      velocity = {1,2},
      texture = "assets/textures/particles/glitter_silver.tga",
      lifetime = {2,2},
      colorAnimation = false,
      color0 = {1,1,2},
      opacity = 1,
      fadeIn = 0,
      fadeOut = 2,
      size = {0.1, 0.2},
      gravity = {0,-10,0},
      clampToGroundPlane = true,
      airResistance = 1,
      rotationSpeed = 0.7,
      blendMode = "Additive",
    },
    {
      emissionRate = 15,
      emissionTime = 0,
      maxParticles = 1000,
      boxMin = {0,0,0},
      boxMax = {0,0,0},
      sprayAngle = {0,360},
      velocity = {0,0},
      objectSpace = true,
      texture = "assets/textures/particles/lightning01.tga",
      frameRate = 4,
      frameSize = 256,
      frameCount = 4,
      lifetime = {0.1,0.3},
      color0 = {1.5,1.5,1.5},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.1,
      size = {0.25, 2.0},
      gravity = {0,0,0},
      airResistance = 5,
      rotationSpeed = 1,
      blendMode = "Additive",
    },
    -- glow
    {
      spawnBurst = true,
      maxParticles = 1,
      boxMin = {0,0,0.0},
      boxMax = {0,0,0.0},
      sprayAngle = {0,0},
      velocity = {0,0},
      texture = "assets/textures/particles/glow.tga",
      lifetime = {1000000, 1000000},
      colorAnimation = false,
      color0 = {0.25,0.32,0.5},
      opacity = 0.3,
      size = {1,1},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 2,
      blendMode = "Additive",
      objectSpace = true,
    }
  }
}

-- fire ------------------------------------------------------------------------

defineParticleSystem{
  name = "flashflare",
  emitters = {
    -- glow
    {
      spawnBurst = true,
      maxParticles = 1,
      boxMin = {0, 0, 0},
      boxMax = {0, 0, 0},
      sprayAngle = {0,30},
      velocity = {0,0},
      texture = "assets/textures/particles/glow.tga",
      lifetime = {3, 3},
      color0 = {2, 1, 0.5},
      opacity = 0.25,
      fadeIn = 0,
      fadeOut = 3,
      size = {7, 7},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 0,
      blendMode = "Additive",
    },
    -- sparkles
    {
      emissionRate = 200,
      emissionTime = 2,
      maxParticles = 500,
      boxMin = {-0.5, 0,-0.5},
      boxMax = { 0.5, 0, 0.5},
      sprayAngle = {-30,30},
      velocity = {3,6},
      objectSpace = false,
      texture = "assets/textures/particles/glitter_gold.tga",
      lifetime = {1,2},
      color0 = {7,6,5},
      opacity = 1,
      fadeIn = 0,
      fadeOut = 1,
      size = {0.01, 0.1},
      gravity = {0,-10,0},
      clampToGroundPlane = true,
      airResistance = 0.01,
      rotationSpeed = 10,
      blendMode = "Additive",
    },
    -- glow sparkles
    {
      emissionRate = 30,
      emissionTime = 3,
      maxParticles = 100,
      boxMin = {-1, 0.0,-1},
      boxMax = { 1, 1.5, 1},
      sprayAngle = {0,180},
      velocity = {0.1,0.5},
      texture = "assets/textures/particles/glow.tga",
      lifetime = {0.2, 0.6},
      color0 = {10,8,6},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 3.5,
      size = {0.3, 1.8},
      gravity = {0,1.5,0},
      airResistance = 1,
      rotationSpeed = 0,
      blendMode = "Additive",
    },
    -- sparkles
    {
      spawnBurst = true,
      maxParticles = 1000,
      boxMin = {-1.3, 0.0, -1.3 },
      boxMax = { 1.3, 0.1,  1.3 },
      sprayAngle = {0,180},
      velocity = {2,5},
      objectSpace = false,
      texture = "assets/textures/particles/glitter_gold.tga",
      lifetime = {0.5,1},
      color0 = {10,8,6},
      opacity = 1,
      fadeIn = 0,
      fadeOut = 1,
      size = {0.05, 0.1},
      gravity = {0,0,0},
      airResistance = 0.01,
      rotationSpeed = 3,
      blendMode = "Additive",
    },
    -- sparks
    {
      spawnBurst = true,
      maxParticles = 400,
      boxMin = {-1, 0,-1},
      boxMax = { 1, 0, 1},
      sprayAngle = {-15,15},
      velocity = {1.5,4.5},
      objectSpace = true,
      texture = "assets/textures/particles/glitter_gold.tga",
      lifetime = {1.5,2.5},
      color0 = {5,4,3},
      opacity = 1,
      fadeIn = 0.2,
      fadeOut = 2,
      size = {0.03, 0.05},
      gravity = {0,1,0},
      airResistance = 0.5,
      rotationSpeed = 1,
      blendMode = "Additive",
    },
    -- core burst
    {
      emissionRate = 100,
      emissionTime = 1.5,
      maxParticles = 100,
      boxMin = {0,0,0},
      boxMax = {0,0,0},
      sprayAngle = {0,360},
      velocity = {0.6, 0.6},
      texture = "assets/textures/particles/torch_flame.tga",
      frameRate = 35,
      frameSize = 64,
      frameCount = 16,
      lifetime = {0.4, 1.8},
      color0 = {2, 1, 0.5},
      opacity = 1,
      fadeIn = 0.15,
      fadeOut = 0.3,
      size = {0.5, 0.95},
      gravity = {0,0,0},
      airResistance = 0.1,
      rotationSpeed = 10,
      blendMode = "Additive",
      objectSpace = true,
    },
    -- lightning core
    {
      emissionRate = 20,
      emissionTime = 0.5,
      maxParticles = 3,
      boxMin = { 0,0,0 },
      boxMax = { 0,0,0 },
      sprayAngle = {0,360},
      velocity = {0,0},
      texture = path.."textures/particles/lightning_ball.tga",
      lifetime = {0.4,0.5},
      color0 = {4, 2, 1},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.3,
      size = {0.8, 2.2},
      gravity = {0,0,0},
      airResistance = 5,
      rotationSpeed = -15,
      blendMode = "Additive",
      objectSpace = true,
    },
  }
}

defineParticleSystem{
  name = "flashflare_screen",
  emitters = {
    {
      spawnBurst = true,
      maxParticles = 1000,
      sprayAngle = {0,360},
      velocity = {0,0.3},
      boxMin = {-1.1,-0.9,1},
      boxMax = {1.1,0.9,1},
      objectSpace = true,
      texture = "assets/textures/particles/poison_cloud.tga",
      lifetime = {12, 13},
      color0 = {2, 1, 0.5},
      opacity = 0.6,
      fadeIn = 0.001,
      fadeOut = 3,
      size = {0.15, 0.44},
      gravity = {0,0,0},
      airResistance = 0.5,
      rotationSpeed = 2,
      blendMode = "Translucent",
    },
    -- glow
    {
      spawnBurst = true,
      emissionRate = 1,
      emissionTime = 0,
      maxParticles = 1,
      boxMin = {0,0,1},
      boxMax = {0,0,1},
      sprayAngle = {0,30},
      velocity = {0,0},
      texture = "assets/textures/particles/glow.tga",
      lifetime = {12, 12},
      color0 = {2, 1, 0.5},
      opacity = 0.5,
      fadeIn = 0.3,
      fadeOut = 3,
      size = {3, 3},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 2,
      blendMode = "Translucent",
      objectSpace = true,
    }
  }
}

defineParticleSystem{
  name = "fire_aura",
  emitters = {
    -- sparkles
    {
      emissionRate = 20,
      emissionTime = 1,
      maxParticles = 20,
      boxMin = {-1.3, -0.3,-1.3 },
      boxMax = { 1.3,  1.5, 1.3 },
      sprayAngle = {0,180},
      velocity = {0.1,0.5},
      objectSpace = false,
      texture = "assets/textures/particles/glitter_gold.tga",
      lifetime = {0.4,1},
      color0 = {1.8*1.5,1.8*1.5,1.2*1.5},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.1,
      size = {0.03, 0.1},
      gravity = {0,2.3,0},
      airResistance = 0.01,
      rotationSpeed = 10,
      blendMode = "Additive",
    },
  }
}

-- air -------------------------------------------------------------------------

defineParticleSystem{
  name = "sleep_trap",
  emitters = {
    -- glow
    {
      spawnBurst = true,
      maxParticles = 1,
      boxMin = {0, 0, 0},
      boxMax = {0, 0, 0},
      sprayAngle = {0,30},
      velocity = {0,0},
      texture = "assets/textures/particles/glow.tga",
      lifetime = {3, 3},
      color0 = {1,1,2},
      opacity = 0.25,
      fadeIn = 0,
      fadeOut = 3,
      size = {7, 7},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 0,
      blendMode = "Additive",
    },
    -- sparkles
    {
      emissionRate = 200,
      emissionTime = 2,
      maxParticles = 500,
      boxMin = {-0.5, 0,-0.5},
      boxMax = { 0.5, 0, 0.5},
      sprayAngle = {-30,30},
      velocity = {3,6},
      objectSpace = false,
      texture = "assets/textures/particles/glitter_silver.tga",
      lifetime = {1,2},
      color0 = {5,6,7},
      opacity = 1,
      fadeIn = 0,
      fadeOut = 1,
      size = {0.01, 0.1},
      gravity = {0,-10,0},
      clampToGroundPlane = true,
      airResistance = 0.01,
      rotationSpeed = 10,
      blendMode = "Additive",
    },
    -- glow sparkles
    {
      emissionRate = 30,
      emissionTime = 3,
      maxParticles = 100,
      boxMin = {-1, 0.0,-1},
      boxMax = { 1, 1.5, 1},
      sprayAngle = {0,180},
      velocity = {0.1,0.5},
      texture = "assets/textures/particles/glow.tga",
      lifetime = {0.2, 0.6},
      colorAnimation = false,
      color0 = {6,8,10},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 3.5,
      size = {0.3, 1.8},
      gravity = {0,1.5,0},
      airResistance = 1,
      rotationSpeed = 0,
      blendMode = "Additive",
    },
    -- sparkles
    {
      spawnBurst = true,
      maxParticles = 1000,
      boxMin = {-1.3, 0.0, -1.3 },
      boxMax = { 1.3, 0.1,  1.3 },
      sprayAngle = {0,180},
      velocity = {2,5},
      objectSpace = false,
      texture = "assets/textures/particles/glitter_silver.tga",
      lifetime = {0.5,1},
      color0 = {10,6,8},
      opacity = 1,
      fadeIn = 0,
      fadeOut = 1,
      size = {0.05, 0.1},
      gravity = {0,0,0},
      airResistance = 0.01,
      rotationSpeed = 3,
      blendMode = "Additive",
    },
    -- sparks
    {
      spawnBurst = true,
      maxParticles = 400,
      boxMin = {-1, 0,-1},
      boxMax = { 1, 0, 1},
      sprayAngle = {-15,15},
      velocity = {1.5,4.5},
      objectSpace = true,
      texture = "assets/textures/particles/glitter_silver.tga",
      lifetime = {1.5,2.5},
      color0 = {3,3,6},
      opacity = 1,
      fadeIn = 0.2,
      fadeOut = 2,
      size = {0.03, 0.05},
      gravity = {0,1,0},
      airResistance = 0.5,
      rotationSpeed = 1,
      blendMode = "Additive",
    },
    -- core burst
    {
      emissionRate = 100,
      emissionTime = 1.5,
      maxParticles = 100,
      boxMin = {0,0,0},
      boxMax = {0,0,0},
      sprayAngle = {0,360},
      velocity = {0.6, 0.6},
      texture = "assets/textures/particles/lightning01.tga",
      frameRate = 4,
      frameSize = 256,
      frameCount = 4,
      lifetime = {0.4, 1.8},
      color0 = {1,1,1},
      opacity = 1,
      fadeIn = 0.15,
      fadeOut = 0.3,
      size = {0.5, 0.95},
      gravity = {0,0,0},
      airResistance = 0.1,
      rotationSpeed = 10,
      blendMode = "Additive",
      objectSpace = true,
    },
    -- lightning core
    {
      emissionRate = 20,
      emissionTime = 0.5,
      maxParticles = 3,
      boxMin = { 0,0,0 },
      boxMax = { 0,0,0 },
      sprayAngle = {0,360},
      velocity = {0,0},
      texture = path.."textures/particles/lightning_ball.tga",
      lifetime = {0.4,0.5},
      color0 = {1,1,5},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.3,
      size = {0.8, 2.2},
      gravity = {0,0,0},
      airResistance = 5,
      rotationSpeed = -15,
      blendMode = "Additive",
      objectSpace = true,
    },
  }
}

-- water -----------------------------------------------------------------------

defineParticleSystem{
  name = "freeze_trap",
  emitters = {
    -- glow
    {
      spawnBurst = true,
      maxParticles = 1,
      boxMin = {0, 0, 0},
      boxMax = {0, 0, 0},
      sprayAngle = {0,30},
      velocity = {0,0},
      texture = "assets/textures/particles/glow.tga",
      lifetime = {3, 3},
      color0 = {0,1,2},
      opacity = 0.25,
      fadeIn = 0,
      fadeOut = 3,
      size = {7, 7},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 0,
      blendMode = "Additive",
    },
    -- ice shards
    {
      emissionRate = 200,
      emissionTime = 2,
      maxParticles = 500,
      boxMin = {-0.5, 0,-0.5},
      boxMax = { 0.5, 0, 0.5},
      sprayAngle = {-30,30},
      velocity = {3,6},
      objectSpace = false,
      texture = "assets/textures/particles/ice_shard.tga",
      frameRate = 30,
      frameSize = 64,
      frameCount = 32,
      lifetime = {1,2},
      color0 = {4,6,8},
      opacity = 1,
      fadeIn = 0,
      fadeOut = 1,
      size = {0.01, 0.1},
      gravity = {0,-10,0},
      clampToGroundPlane = true,
      airResistance = 0.01,
      rotationSpeed = 10,
      blendMode = "Translucent",
    },
    -- glow sparkles
    {
      emissionRate = 30,
      emissionTime = 3,
      maxParticles = 100,
      boxMin = {-1, 0.0,-1},
      boxMax = { 1, 1.5, 1},
      sprayAngle = {0,180},
      velocity = {0.1,0.5},
      texture = "assets/textures/particles/glow.tga",
      lifetime = {0.2, 0.6},
      color0 = {6,8,10},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 3.5,
      size = {0.3, 1.8},
      gravity = {0,1.5,0},
      airResistance = 1,
      rotationSpeed = 0,
      blendMode = "Additive",
    },
    -- sparkles
    {
      spawnBurst = true,
      maxParticles = 1000,
      boxMin = {-1.3, 0.0, -1.3 },
      boxMax = { 1.3, 0.1,  1.3 },
      sprayAngle = {0,180},
      velocity = {2,5},
      objectSpace = false,
      texture = "assets/textures/particles/glitter_silver.tga",
      lifetime = {0.5,1},
      color0 = {6,8,10},
      opacity = 1,
      fadeIn = 0,
      fadeOut = 1,
      size = {0.05, 0.1},
      gravity = {0,0,0},
      airResistance = 0.01,
      rotationSpeed = 3,
      blendMode = "Additive",
    },
    -- sparks
    {
      spawnBurst = true,
      maxParticles = 400,
      boxMin = {-1, 0,-1},
      boxMax = { 1, 0, 1},
      sprayAngle = {-15,15},
      velocity = {1.5,4.5},
      objectSpace = true,
      texture = "assets/textures/particles/glitter_silver.tga",
      lifetime = {1.5,2.5},
      color0 = {2,4,6},
      opacity = 1,
      fadeIn = 0.2,
      fadeOut = 2,
      size = {0.03, 0.05},
      gravity = {0,1,0},
      airResistance = 0.5,
      rotationSpeed = 1,
      blendMode = "Additive",
    },
    -- core burst
    {
      emissionRate = 100,
      emissionTime = 1.5,
      maxParticles = 100,
      boxMin = {0,0,0},
      boxMax = {0,0,0},
      sprayAngle = {0,360},
      velocity = {0.6, 1.6},
      texture = "assets/textures/particles/ice_guardian_smoke.tga",
      lifetime = {0.4, 1.8},
      color0 = {1,1,1},
      opacity = 1,
      fadeIn = 0.15,
      fadeOut = 0.3,
      size = {0.5, 0.95},
      gravity = {0,0,0},
      airResistance = 0.1,
      rotationSpeed = 10,
      blendMode = "Translucent",
      objectSpace = true,
    },
    -- lightning core
    {
      emissionRate = 20,
      emissionTime = 0.5,
      maxParticles = 3,
      boxMin = { 0,0,0 },
      boxMax = { 0,0,0 },
      sprayAngle = {0,360},
      velocity = {0,0},
      texture = path.."textures/particles/lightning_ball.tga",
      lifetime = {0.4,0.5},
      color0 = {1,2,4},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.3,
      size = {0.8, 2.2},
      gravity = {0,0,0},
      airResistance = 5,
      rotationSpeed = -15,
      blendMode = "Additive",
      objectSpace = true,
    },
  }
}

defineParticleSystem{
  name = "ice_screen",
  emitters = {
    -- fog
    {
      emissionRate = 100,
      emissionTime = 3,
      maxParticles = 200,
      boxMin = {-0.5, -1.25,-0.5},
      boxMax = { 0.5, 1.25, 0.5},
      sprayAngle = {0,360},
      velocity = {0.1,0.2},
      objectSpace = true,
      texture = "assets/textures/particles/fog.tga",
      lifetime = {2,2},
      color0 = {0.803922, 0.952941, 1.652941},
      opacity = 0.2,
      fadeIn = 0.1,
      fadeOut = 0.1,
      size = {1.5, 1.5},
      gravity = {0,0,0},
      airResistance = 0.1,
      rotationSpeed = 0.3,
      blendMode = "Additive",
    },
    -- stars
    {
      emissionRate = 100,
      emissionTime = 3,
      maxParticles = 400,
      boxMin = {-0.6, -1,-0.6},
      boxMax = { 0.6, 1, 0.6},
      sprayAngle = {0,360},
      velocity = {0.2,0.2},
      objectSpace = true,
      color0 = {0.803922, 0.852941, 1.452941},
      texture = "assets/textures/particles/teleporter.tga",
      lifetime = {1,1},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.1,
      size = {0.1, 0.2},
      gravity = {0,-4,0},
      airResistance = 0.5,
      rotationSpeed = 2,
      blendMode = "Additive",
    }
  }
}

defineParticleSystem{
  name = "hit_ice_block",
  emitters = {
    {
      spawnBurst = true,
      maxParticles = 20,
      boxMin = {-1.5,0,-1.5},
      boxMax = { 1.5,3, 1.5},
      sprayAngle = {-60,60},
      velocity = {1,2},
      objectSpace = false,
      texture = "assets/textures/particles/ice_shard.tga",
      frameRate = 30,
      frameSize = 64,
      frameCount = 32,
      lifetime = {2,2},
      color0 = {1,1,1},
      opacity = 1,
      fadeIn = 0,
      fadeOut = 0.1,
      size = {0.1, 0.2},
      gravity = {0,-10,0},
      airResistance = 0.2,
      rotationSpeed = 1,
      blendMode = "Translucent",
      clampToGroundPlane = true,
    },
    {
      spawnBurst = true,
      maxParticles = 10,
      boxMin = {-1.5,-1,-1.5},
      boxMax = { 1.5,3, 1.5},
      sprayAngle = {0,100},
      velocity = {0.5,2},
      objectSpace = false,
      texture = "assets/textures/particles/ice_guardian_smoke.tga",
      lifetime = {0.3,1.5},
      color0 = {1,1,1},
      opacity = 0.3,
      fadeIn = 0.1,
      fadeOut = 0.3,
      size = {0.5, 1.5},
      gravity = {0,0,0},
      airResistance = 2,
      rotationSpeed = 1,
      blendMode = "Translucent",
    },
  }
}

defineParticleSystem{
  name = "ice_aura",
  emitters = {
    -- sparkles
    {
      emissionRate = 20,
      emissionTime = 1,
      maxParticles = 20,
      boxMin = {-1.3,  1.5,-1.3 },
      boxMax = { 1.3,  3.3, 1.3 },
      sprayAngle = {0,180},
      velocity = {0.1,0.5},
      objectSpace = false,
      texture = "assets/textures/particles/glitter_silver.tga",
      lifetime = {0.4,1},
      color0 = {1.2*1.5,1.8*1.5,1.8*1.5},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.1,
      size = {0.03, 0.1},
      gravity = {0,-2.3,0},
      airResistance = 0.01,
      rotationSpeed = 10,
      blendMode = "Additive",
    },
  }
}

-- earth -----------------------------------------------------------------------

defineParticleSystem{
  name = "poison_fireflies",
  emitters = {
        -- fireflies
    {
      emissionRate = 20,
      emissionTime = 0,
      maxParticles = 100,
      boxMin = {-0.75,-0.5,-0.75},
      boxMax = { 0.75,0.5, 0.75},
      sprayAngle = {0,360},
      velocity = {0.1,0.5},
      objectSpace = true,
      texture = "assets/textures/particles/firefly_dif.tga",
      lifetime = {2.5,5},
      color0 = {1.6,1.8,1.8},
      opacity = 1,
      fadeIn = 1,
      fadeOut = 1,
      size = {0.03, 0.1},
      gravity = {0,0,0},
      airResistance = 0.01,
      rotationSpeed = 10,
      blendMode = "Additive",
    },

  }
}

defineParticleSystem{
  name = "poison_cloud_large",
  emitters = {
    -- blast
    {
      spawnBurst = true,
      maxParticles = 20,
      boxMin = {-0.5, -0.4,-0.5},
      boxMax = { 0.5,  0.2, 0.5},
      sprayAngle = {0,360},
      velocity = {0.1,0.7},
      objectSpace = true,
      texture = "assets/textures/particles/poison_cloud.tga",
      lifetime = {1.5,1.5},
      color0 = {0.5, 0.5, 0.5},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 1,
      size = {2,2},
      gravity = {0,0,0},
      airResistance = 0.1,
      rotationSpeed = 0.5,
      blendMode = "Translucent",
    },
    -- fog
    {
      emissionRate = 25,
      emissionTime = 0,
      maxParticles = 1900,
      boxMin = {-1.4, -1.0*1.35,-1.4},
      boxMax = { 1.4,  0.5*1.35, 1.4},
      sprayAngle = {0,360},
      velocity = {0.1,0.7*1.35},
      objectSpace = true,
      texture = "assets/textures/particles/smoke_01.tga",
      lifetime = {2,2},
      color0 = {0.29, 0.29, 0.145},
      opacity = 0.8,
      fadeIn = 1,
      fadeOut = 1,
      size = {1.4*1.5, 1.75*1.5},
      gravity = {0,0,0},
      airResistance = 0.1,
      rotationSpeed = 0.1,
      blendMode = "Translucent",
    },
    -- fog
    {
      emissionRate = 5,
      emissionTime = 0,
      maxParticles = 1900,
      boxMin = {-1.4, -0.5*1.35,-1.4},
      boxMax = { 1.4,  0.5*1.35, 1.4},
      sprayAngle = {0,360},
      velocity = {0.1,0.3},
      objectSpace = true,
      texture = "assets/textures/particles/poison_cloud.tga",
      lifetime = {2,2},
      color0 = {1,1,1},
      opacity = 0.8,
      fadeIn = 1,
      fadeOut = 1,
      size = {1.4*1.25, 1.75*1.25},
      gravity = {0,0,0},
      airResistance = 0.1,
      rotationSpeed = 0.1,
      blendMode = "Translucent",
    },
    -- pollen
    {
      emissionRate = 770,
      emissionTime = 0,
      maxParticles = 1900,
      boxMin = {-1*1.4,-1.3*1.25,-1*1.4},
      boxMax = { 1*1.4, 0.8*1.25, 1*1.4},
      sprayAngle = {0,30},
      velocity = {0.5,1.0},
      objectSpace = true,
      texture = "assets/textures/particles/smoke_01.tga",
      lifetime = {1,1},
      color0 = {1.5,1.5,0.5},
      opacity = 0.15,
      fadeIn = 0.1,
      fadeOut = 0.3,
      size = {0.03, 0.05},
      gravity = {0,-1.2,0},
      airResistance = 0.1,
      rotationSpeed = 2,
      blendMode = "Additive",
    },
    -- glow
    {
      spawnBurst = true,
      emissionRate = 1,
      emissionTime = 0,
      maxParticles = 1,
      boxMin = {0,0,-0.1},
      boxMax = {0,0,-0.1},
      sprayAngle = {0,30},
      velocity = {0,0},
      texture = "assets/textures/particles/glow.tga",
      lifetime = {0.5, 0.5},
      colorAnimation = false,
      color0 = {0.1, 0.12, 0.1},
      opacity = 1,
      fadeIn = 0.01,
      fadeOut = 0.5,
      size = {2, 2},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 2,
      blendMode = "Additive",
    },
  }
}

defineParticleSystem{
  name = "rock_spell",
  emitters = {
    -- fog
    {
      emissionRate = 200,
      emissionTime = 0,
      maxParticles = 1000,
      boxMin = { 0, 0, 0},
      boxMax = { 0, 0, 0},
      sprayAngle = {0,360},
      velocity = {0.1,0.2},
      objectSpace = false,
      texture = "assets/textures/particles/fog.tga",
      lifetime = {0.2,0.4},
      color0 = {0.25, 0.25, 0.25},
      opacity = 0.5,
      fadeIn = 0.01,
      fadeOut = 0.6,
      size = {0.2, 0.3},
      gravity = {0,-1,0},
      airResistance = 0.1,
      rotationSpeed = 3,
      blendMode = "Translucent",
    },
  }
}

defineParticleSystem{
  name = "rock_blast",
  emitters = {
    -- fog
    {
      spawnBurst = true,
      maxParticles = 20,
      sprayAngle = {0,360},
      velocity = {0.2,0.9},
      objectSpace = true,
      texture = "assets/textures/particles/fog.tga",
      lifetime = {0.2,0.7},
      color0 = {0.25, 0.25, 0.25},
      opacity = 0.5,
      fadeIn = 0.05,
      fadeOut = 0.3,
      size = {0.3, 0.7},
      gravity = {0,-1,0},
      airResistance = 0.5,
      rotationSpeed = 1,
      blendMode = "Translucent",
    },
  }
}

defineParticleSystem{
  name = "entangling_roots_trap",
  emitters = {
    -- glow
    {
      spawnBurst = true,
      maxParticles = 1,
      boxMin = {0, 0, 0},
      boxMax = {0, 0, 0},
      sprayAngle = {0,30},
      velocity = {0,0},
      texture = "assets/textures/particles/glow.tga",
      lifetime = {3, 3},
      color0 = {1,2,0},
      opacity = 0.25,
      fadeIn = 0,
      fadeOut = 3,
      size = {7, 7},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 0,
      blendMode = "Additive",
    },
    -- leaves
    {
      emissionRate = 50,
      emissionTime = 2,
      maxParticles = 500,
      boxMin = {-0.5, 0,-0.5},
      boxMax = { 0.5, 0, 0.5},
      sprayAngle = {-30,30},
      velocity = {2,4},
      objectSpace = false,
      texture = "assets/textures/particles/particle_leaf_sequence.tga",
      frameRate = 18,
      frameSize = 64,
      frameCount = 36,
      lifetime = {2,3},
      color0 = {0.3,1.7,1},
      opacity = 1,
      fadeIn = 0,
      fadeOut = 1,
      size = {0.1, 0.5},
      gravity = {0,-10,0},
      clampToGroundPlane = true,
      airResistance = 0.01,
      rotationSpeed = 0,
      blendMode = "Translucent",
    },
    -- glow sparkles
    {
      emissionRate = 30,
      emissionTime = 3,
      maxParticles = 100,
      boxMin = {-1, 0.0,-1},
      boxMax = { 1, 1.5, 1},
      sprayAngle = {0,180},
      velocity = {0.1,0.5},
      texture = "assets/textures/particles/glow.tga",
      lifetime = {0.2, 0.6},
      color0 = {6,10,8},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 3.5,
      size = {0.3, 1.8},
      gravity = {0,1.5,0},
      airResistance = 1,
      rotationSpeed = 0,
      blendMode = "Additive",
    },
    -- sparkles
    {
      spawnBurst = true,
      maxParticles = 1000,
      boxMin = {-1.3, 0.0, -1.3 },
      boxMax = { 1.3, 0.1,  1.3 },
      sprayAngle = {0,180},
      velocity = {2,5},
      objectSpace = false,
      texture = "assets/textures/particles/glitter_silver.tga",
      lifetime = {0.5,1},
      color0 = {8,10,6},
      opacity = 1,
      fadeIn = 0,
      fadeOut = 1,
      size = {0.05, 0.1},
      gravity = {0,0,0},
      airResistance = 0.01,
      rotationSpeed = 3,
      blendMode = "Additive",
    },
    -- sparks
    {
      spawnBurst = true,
      maxParticles = 400,
      boxMin = {-1, 0,-1},
      boxMax = { 1, 0, 1},
      sprayAngle = {-15,15},
      velocity = {1.5,4.5},
      objectSpace = true,
      texture = "assets/textures/particles/glitter_silver.tga",
      lifetime = {1.5,2.5},
      color0 = {2,6,4},
      opacity = 1,
      fadeIn = 0.2,
      fadeOut = 2,
      size = {0.03, 0.05},
      gravity = {0,1,0},
      airResistance = 0.5,
      rotationSpeed = 1,
      blendMode = "Additive",
    },
    -- core burst
    {
      emissionRate = 100,
      emissionTime = 1.5,
      maxParticles = 100,
      boxMin = {0,0,0},
      boxMax = {0,0,0},
      sprayAngle = {0,360},
      velocity = {0.6, 1.6},
      texture = "assets/textures/particles/poison_cloud.tga",
      lifetime = {0.4, 1.8},
      color0 = {1,1,1},
      opacity = 0.1,
      fadeIn = 0.15,
      fadeOut = 0.3,
      size = {1,2},
      gravity = {0,0,0},
      airResistance = 0.1,
      rotationSpeed = 10,
      blendMode = "Translucent",
      objectSpace = true,
    },
    -- lightning core
    {
      emissionRate = 20,
      emissionTime = 0.5,
      maxParticles = 3,
      boxMin = { 0,0,0 },
      boxMax = { 0,0,0 },
      sprayAngle = {0,360},
      velocity = {0,0},
      texture = path.."textures/particles/lightning_ball.tga",
      lifetime = {0.4,0.5},
      color0 = {1,5,1},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.3,
      size = {0.8, 2.2},
      gravity = {0,0,0},
      airResistance = 5,
      rotationSpeed = -15,
      blendMode = "Additive",
      objectSpace = true,
    },
  }
}

-- fire & air ------------------------------------------------------------------

defineParticleSystem{
  name = "time_bolt",
  emitters = {
    -- stars
    {
      emissionRate = 200,
      emissionTime = 0,
      maxParticles = 1000,
      sprayAngle = {90,90},
      velocity = {0.5,0.5},
      objectSpace = false,
      texture = "assets/textures/particles/teleporter.tga",
      lifetime = {0.5,0.5},
      colorAnimation = true,
      color0 = {2.1,0.0,0.0},
      color1 = {2.0,1.0,0.5},
      color2 = {1.9,1.5,1.0},
      color3 = {1.8,1.8,1.8},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.1,
      size = {0.1, 0.3},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 2,
      blendMode = "Additive",
    },

    -- small stars
    {
      emissionRate = 300,
      emissionTime = 0,
      maxParticles = 1000,
      sprayAngle = {90,90},
      velocity = {0.5,0.5},
      objectSpace = false,
      texture = "assets/textures/particles/teleporter.tga",
      lifetime = {0.5,0.5},
      colorAnimation = true,
      color0 = {1.9,0.0,0.0},
      color1 = {1.8,1.0,0.5},
      color2 = {1.7,1.5,1.0},
      color3 = {1.6,1.8,1.8},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.1,
      size = {0.05, 0.1},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 2,
      blendMode = "Additive",
    },
  }
}

-- earth & fire ----------------------------------------------------------------

defineParticleSystem{
  name = "volcanic_eruption",
  emitters = {
    -- smoke
    {
      spawnBurst = true,
      maxParticles = 10,
      boxMin = {-1.0, 0.5,-1.0},
      boxMax = { 1.0, 1.5, 1.0},
      sprayAngle = {0,100},
      velocity = {0.1, 0.5},
      texture = "assets/textures/particles/smoke_01.tga",
      lifetime = {1,2},
      color0 = {0.25, 0.50, 0.17},
      opacity = 1,
      fadeIn = 0.3,
      fadeOut = 0.9,
      size = {2, 3},
      gravity = {0,0,0},
      airResistance = 0.1,
      rotationSpeed = 0.5,
      blendMode = "Translucent",
    },

    -- flames
    {
      spawnBurst = true,
      maxParticles = 50,
      sprayAngle = {0,360},
      boxMin = {-1.0, 0.5,-1.0},
      boxMax = { 1.0, 1.5, 1.0},
      velocity = {3,7},
      objectSpace = true,
      texture = "assets/textures/particles/torch_flame.tga",
      frameRate = 35,
      frameSize = 64,
      frameCount = 16,
      lifetime = {0.2,0.6},
      color0 = {1, 0.5, 0.25},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.3,
      size = {1, 2},
      gravity = {0,10,0},
      airResistance = 0.5,
      rotationSpeed = 2,
      blendMode = "Additive",
    },

    -- fog
    {
      spawnBurst = true,
      maxParticles = 5,
      sprayAngle = {0,360},
      velocity = {0,3},
      objectSpace = true,
      texture = "assets/textures/particles/fog.tga",
      lifetime = {0.4,0.6},
      color0 = {1, 0.5, 0.25},
      opacity = 0.7,
      fadeIn = 0.1,
      fadeOut = 0.3,
      size = {1, 2},
      gravity = {0,0,0},
      airResistance = 0.5,
      rotationSpeed = 1,
      blendMode = "Additive",
    },

    -- glow
    {
      spawnBurst = true,
      emissionRate = 1,
      emissionTime = 0,
      maxParticles = 1,
      boxMin = {0,0,-0.1},
      boxMax = {0,0,-0.1},
      sprayAngle = {0,30},
      velocity = {0,0},
      texture = "assets/textures/particles/glow.tga",
      lifetime = {1, 1},
      colorAnimation = false,
      color0 = {2, 2, 2},
      opacity = 1,
      fadeIn = 0.01,
      fadeOut = 0.5,
      size = {3, 3},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 2,
      blendMode = "Additive",
      depthBias = 3,
    },

    -- glow
    {
      spawnBurst = true,
      emissionRate = 1,
      emissionTime = 0,
      maxParticles = 1,
      boxMin = {0,0,-0.1},
      boxMax = {0,0,-0.1},
      sprayAngle = {0,30},
      velocity = {0,0},
      texture = "assets/textures/particles/glow.tga",
      lifetime = {1, 1},
      colorAnimation = false,
      color0 = {1, 0.5, 0},
      opacity = 1,
      fadeIn = 0.01,
      fadeOut = 0.5,
      size = {8, 8},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 2,
      blendMode = "Additive",
      depthBias = 3,
    }
  }
}

-- air & earth -----------------------------------------------------------------

defineParticleSystem{
  name = "magic_bridge_init",
  emitters = {
    -- stars
    {
      emissionRate = 100,
      emissionTime = 1,
      maxParticles = 200,
      boxMin = {-1.5,3,-1.5},
      boxMax = { 1.5,3, 1.5},
      sprayAngle = {0,30},
      velocity = {0.0,0.1},
      objectSpace = false,
      texture = "assets/textures/particles/glitter_silver.tga",
      lifetime = {1,1.7},
      color0 = {1.5,1.0,1.25},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.5,
      size = {0.05, 0.15},
      gravity = {0,-5,0},
      airResistance = 0.1,
      rotationSpeed = 2,
      blendMode = "Additive",
      clampToGroundPlane = true,
    },
    -- stars
    {
      emissionRate = 400,
      emissionTime = 1,
      maxParticles = 400,
      boxMin = {-1.5,3,-1.5},
      boxMax = { 1.5,3, 1.5},
      sprayAngle = {0,30},
      velocity = {0.0,0.1},
      objectSpace = false,
      texture = "assets/textures/particles/glitter_silver.tga",
      lifetime = {1,1},
      color0 = {1.5*1.5, 1.0*1.5, 1.25*1.5},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.5,
      size = {0.05, 0.25},
      gravity = {0,-5,0},
      airResistance = 0.1,
      rotationSpeed = 2,
      blendMode = "Additive",
      clampToGroundPlane = true,
    },
  }
}

-- air, water & earth ----------------------------------------------------------

defineParticleSystem{
  name = "life_drain",
  emitters = {
    {
      emissionRate = 16,
      emissionTime = 0,
      maxParticles = 128,
      sprayAngle = {0,90},
      velocity = {0.1,0.3},
      objectSpace = false,
      texture = "assets/textures/particles/blood.tga",
      frameRate = 40,
      frameSize = 32,
      frameCount = 40,
      lifetime = {1.6,16},
      color0 = {10,10,10},
      opacity = 0.5,
      fadeIn = 0.8,
      fadeOut = 0.8,
      size = {0.05, 0.3},
      gravity = {0,-0.1,0},
      airResistance = 0.1,
      rotationSpeed = 0.2,
      blendMode = "Translucent",
    },
  }
}

defineParticleSystem{
  name = "drain_life_bolt",
  emitters = {
    -- stars
    {
      emissionRate = 200,
      emissionTime = 0,
      maxParticles = 200,
      sprayAngle = {0,0},
      velocity = {0.5,0.5},
      objectSpace = false,
      texture = "assets/textures/particles/teleporter.tga",
      lifetime = {0.5,0.5},
      colorAnimation = true,
      color0 = {0.0,0.0,1.0},
      color1 = {0.0,0.0,1.0},
      color2 = {0.0,0.5,0.5},
      color3 = {0.0,1.0,0.0},
      opacity = 0.25,
      fadeIn = 0.1,
      fadeOut = 0.1,
      size = {1, 3},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 2,
      blendMode = "Additive",
    },

    -- small stars
    {
      emissionRate = 200,
      emissionTime = 0,
      maxParticles = 200,
      sprayAngle = {0,0},
      velocity = {0.5,0.5},
      objectSpace = false,
      texture = "assets/textures/particles/teleporter.tga",
      lifetime = {0.5,0.5},
      colorAnimation = true,
      color0 = {1.0,1.0,2.0},
      color1 = {1.0,1.0,2.0},
      color2 = {1.0,1.5,1.5},
      color3 = {1.0,2.0,1.0},
      opacity = 0.25,
      fadeIn = 0.1,
      fadeOut = 0.1,
      size = {0.5, 1},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 2,
      blendMode = "Additive",
    },
  }
}

defineParticleSystem{
  name = "blood_hit",
  emitters = {
    -- sparks
    {
      spawnBurst = true,
      maxParticles = 8,
      boxMin = {-0.1, -0.1, -0.1},
      boxMax = { 0.1,  0.1,  0.1},
      sprayAngle = {0,360},
      velocity = {4,6},
      objectSpace = false,
      texture = "assets/textures/particles/teleporter.tga",
      lifetime = {0.2,0.6},
      color0 = {4.0,2.0,1.0},
      opacity = 0.1,
      fadeIn = 0.1,
      fadeOut = 0.3,
      size = {0.05, 0.3},
      gravity = {0,-6,0},
      airResistance = 1,
      rotationSpeed = 2,
      blendMode = "Additive",
    },

    -- fog
    {
      spawnBurst = true,
      maxParticles = 3,
      sprayAngle = {0,360},
      velocity = {0,3},
      objectSpace = true,
      texture = "assets/textures/particles/fog.tga",
      lifetime = {0.4,0.6},
      color0 = {4, 1, 0.6},
      opacity = 0.07,
      fadeIn = 0.1,
      fadeOut = 0.3,
      size = {1, 2},
      gravity = {0,0,0},
      airResistance = 0.5,
      rotationSpeed = 1,
      blendMode = "Additive",
    },

    -- glow
    {
      spawnBurst = true,
      emissionRate = 1,
      emissionTime = 0,
      maxParticles = 1,
      boxMin = {0,0,-0.1},
      boxMax = {0,0,-0.1},
      sprayAngle = {0,30},
      velocity = {0,0},
      texture = "assets/textures/particles/glow.tga",
      lifetime = {0.5, 0.5},
      colorAnimation = false,
      color0 = {1, 1, 1},
      opacity = 0.1,
      fadeIn = 0.01,
      fadeOut = 0.5,
      size = {1, 1},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 2,
      blendMode = "Additive",
    }
  }
}

-- earth, fire & air -----------------------------------------------------------

defineParticleSystem{
  name = "life_steal_bolt",
  emitters = {
    -- stars
    {
      emissionRate = 200,
      emissionTime = 0,
      maxParticles = 200,
      sprayAngle = {0,0},
      velocity = {0.5,0.5},
      objectSpace = false,
      texture = "assets/textures/particles/teleporter.tga",
      lifetime = {0.5,0.5},
      colorAnimation = true,
      color0 = {1.0,0.0,0.0},
      color1 = {1.0,0.0,0.0},
      color2 = {1.0,0.0,0.0},
      color3 = {0.0,1.0,0.0},
      opacity = 0.25,
      fadeIn = 0.1,
      fadeOut = 0.1,
      size = {1, 3},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 2,
      blendMode = "Additive",
    },

    -- small stars
    {
      emissionRate = 200,
      emissionTime = 0,
      maxParticles = 200,
      sprayAngle = {0,0},
      velocity = {0.5,0.5},
      objectSpace = false,
      texture = "assets/textures/particles/teleporter.tga",
      lifetime = {0.5,0.5},
      colorAnimation = true,
      color0 = {2.0,1.0,1.0},
      color1 = {2.0,1.0,1.0},
      color2 = {2.0,1.0,1.0},
      color3 = {1.0,2.0,1.0},
      opacity = 0.25,
      fadeIn = 0.1,
      fadeOut = 0.1,
      size = {0.5, 1},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 2,
      blendMode = "Additive",
    },
  }
}

defineParticleSystem{
  name = "swap_bolt",
  emitters = {
    {
      emissionRate = 128,
      emissionTime = 0,
      maxParticles = 64,
      sprayAngle = {0,360},
      velocity = {1,2},
      objectSpace = false,
      texture = "assets/textures/particles/teleporter.tga",
      lifetime = {0.5,1},
      color0 = {0.67,1,0.33},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.1,
      size = {0.25, 0.5},
      gravity = {0,-10,0},
      airResistance = 5,
      rotationSpeed = 5,
      blendMode = "Additive",
    },
    {
      emissionRate = 128,
      emissionTime = 0,
      maxParticles = 64,
      sprayAngle = {0,360},
      velocity = {1,2},
      objectSpace = false,
      texture = "assets/textures/particles/teleporter.tga",
      lifetime = {0.5,1},
      color0 = {0.33,1,0.67},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.1,
      size = {0.25, 0.5},
      gravity = {0,-10,0},
      airResistance = 5,
      rotationSpeed = -5,
      blendMode = "Additive",
    },
    {
      spawnBurst = true,
      maxParticles = 1,
      sprayAngle = {0,0},
      velocity = {0,0},
      objectSpace = true,
      texture = "assets/textures/lensflare/streaks.tga",
      lifetime = {1000000,1000000},
      color0 = {0.25,1,0.25},
      opacity = 1,
      fadeIn = 0.001,
      fadeOut = 0.001,
      size = {1,1},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = 10,
      blendMode = "Additive",
    },
  }
}

defineParticleSystem{
  name = "teleportation_failed",
  emitters = {
    -- fog
    {
      spawnBurst = true,
      emissionRate = 0,
      emissionTime = 0,
      maxParticles = 10,
      boxMin = {-1.0, 0.5,-1.0},
      boxMax = { 1.0, 2.5, 1.0},
      sprayAngle = {0,360},
      velocity = {0.1,1},
      objectSpace = true,
      texture = "assets/textures/particles/fog.tga",
      lifetime = {0.5,0.5},
      color0 = {0.450490, 0.365000, 0.190294},
      opacity = 0.3,
      fadeIn = 0.2,
      fadeOut = 0.2,
      size = {2, 2},
      gravity = {0,0,0},
      airResistance = 0.1,
      rotationSpeed = 0.3,
      blendMode = "Additive",
    },
    -- stars
    {
      emissionRate = 1000,
      emissionTime = 0.2,
      maxParticles = 1000,
      boxMin = {-1.5,-0.5,-1.5},
      boxMax = { 1.5, 2.5, 1.5},
      sprayAngle = {0,30},
      velocity = {0.5,1.5},
      objectSpace = true,
      texture = "assets/textures/particles/teleporter.tga",
      lifetime = {0.4,0.6},
      color0 = {3.8,0.8,0.8},
      opacity = 1,
      fadeIn = 0.01,
      fadeOut = 0.4,
      size = {0.1, 0.3},
      gravity = {0,-1,0},
      airResistance = 0.1,
      rotationSpeed = 2,
      blendMode = "Additive",
    },
    -- small stars
    {
      emissionRate = 1000,
      emissionTime = 0.2,
      maxParticles = 1000,
      boxMin = {-1.5,-0.5,-1.5},
      boxMax = { 1.5, 2.5, 1.5},
      sprayAngle = {0,30},
      velocity = {0.5,1.0},
      objectSpace = true,
      texture = "assets/textures/particles/teleporter.tga",
      lifetime = {0.4,0.6},
      color0 = {3.6,0.8,0.8},
      opacity = 1,
      fadeIn = 0.01,
      fadeOut = 0.4,
      size = {0.05, 0.1},
      gravity = {0,-0.5,0},
      airResistance = 0.1,
      rotationSpeed = 2,
      blendMode = "Additive",
    }
  }
}

-- fire, air & water -----------------------------------------------------------

defineParticleSystem{
  name = "transfer_bolt",
  emitters = {
    {
      emissionRate = 128,
      emissionTime = 0,
      maxParticles = 64,
      sprayAngle = {0,360},
      velocity = {0,1},
      objectSpace = false,
      texture = "assets/textures/particles/goromorg_lantern.tga",
      frameRate = 35,
      frameSize = 64,
      frameCount = 16,
      lifetime = {0.5,1},
      color0 = {1,1,1},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.1,
      size = {0.05, 0.25},
      gravity = {0,5,0},
      airResistance = 5,
      rotationSpeed = -5,
      blendMode = "Additive",
    },
    {
      emissionRate = 128,
      emissionTime = 0,
      maxParticles = 64,
      sprayAngle = {0,360},
      velocity = {0,1},
      objectSpace = false,
      texture = "assets/textures/particles/torch_flame.tga",
      frameRate = 35,
      frameSize = 64,
      frameCount = 16,
      lifetime = {0.5,1},
      color0 = {1,1,1},
      opacity = 1,
      fadeIn = 0.1,
      fadeOut = 0.1,
      size = {0.05, 0.25},
      gravity = {0,5,0},
      airResistance = 5,
      rotationSpeed = 5,
      blendMode = "Additive",
    },
    {
      spawnBurst = true,
      maxParticles = 1,
      sprayAngle = {0,0},
      velocity = {0,0},
      objectSpace = true,
      texture = "assets/textures/lensflare/streaks.tga",
      lifetime = {1000000,1000000},
      color0 = {0.625,0.25,0.625},
      opacity = 1,
      fadeIn = 0.001,
      fadeOut = 0.001,
      size = {1,1},
      gravity = {0,0,0},
      airResistance = 1,
      rotationSpeed = -10,
      blendMode = "Additive",
    },
  }
}