defineObject{
	name = "ash_elemental",
	baseObject = "base_monster",
	components = {
		{
			class = "Model",
			model = "assets/models/monsters/zarchton.fbx",
			storeSourceData = true,
			enabled = false,
		},
		{
			class = "Animation",
			animations = {
				idle = "assets/animations/monsters/zarchton/zarchton_diving_idle.fbx",
				moveForward = "assets/animations/monsters/zarchton/zarchton_diving_forward.fbx",
				turnLeft = "assets/animations/monsters/zarchton/zarchton_diving_turn_left.fbx",
				turnRight = "assets/animations/monsters/zarchton/zarchton_diving_turn_right.fbx",
				attack = "assets/animations/monsters/zarchton/zarchton_diving_attack.fbx",
				leapAttack = "assets/animations/monsters/zarchton/zarchton_diving_move_attack.fbx",
				getHitFrontLeft = "assets/animations/monsters/zarchton/zarchton_diving_get_hit_front_left.fbx",
				getHitFrontRight = "assets/animations/monsters/zarchton/zarchton_diving_get_hit_front_right.fbx",
				getHitBack = "assets/animations/monsters/zarchton/zarchton_diving_get_hit_back.fbx",
				getHitLeft = "assets/animations/monsters/zarchton/zarchton_diving_get_hit_left.fbx",
				getHitRight = "assets/animations/monsters/zarchton/zarchton_diving_get_hit_right.fbx",
				fall = "assets/animations/monsters/zarchton/zarchton_diving_get_hit_front_left.fbx",
				alert = "assets/animations/monsters/zarchton/zarchton_diving_alert.fbx",
			},
			currentLevelOnly = true,
		},
		{
			class = "Monster",
			meshName = "zarchton_mesh",
			hitSound = "fire_elemental_hit",
			dieSound = "fire_elemental_die",
			hitEffect = "hit_flame",
			capsuleHeight = 0.5,
			capsuleRadius = 0.2,
			collisionRadius = 0.7,
			health = 40,
			evasion = 0,
			flying = true,
			exp = 200,
			immunities = { "sleep", "frozen", "blinded" },
			resistances = {
				fire = "absorb",
				cold = "vulnerable",
				poison = "immune",
			},
			traits = { "elemental" },
			onDie = function(self)
				self.go.sound:fadeOut(1)
			end,
		},
		{
			class = "FireElementalBrain",
			name = "brain",
			sight = 6,			
		},
		{
			class = "MonsterMove",
			name = "move",
			sound = "fire_elemental_walk",
			cooldown = 0,
			animationSpeed = 1.6,
		},
		{
			class = "MonsterTurn",
			name = "turn",
			sound = "fire_elemental_walk",
			animationSpeed = 2,
		},
		{
			class = "MonsterAttack",
			name = "basicAttack",
			attackPower = 15,
			animationSpeed = 2,
			cooldown = 3,
			sound = "fire_elemental_attack",
			onAttack = function(self)
				local dx,dy = getForward(self.go.facing)
				local x,y = self.go.x + dx, self.go.y + dy
				local obj = spawn("ash_blast", self.go.level, x, y, 0, self.go.elevation)
				obj.tiledamager:setAttackPower(40)
				self.go:destroyDelayed()
			end,
		},
		{
			class = "UggardianFlames",
			particleSystem = "ash_elemental",
		},
		{
			class = "Light",
			parentNode = "capsule",
			color = vec(0.1, 0.1, 0.1),
			brightness = 15,
			range = 3.5,
			fillLight = true,
		},
		{
			class = "MonsterChangeAltitude",
			name = "changeAltitude",
			sound = "fire_elemental_walk",
		},
		{
			class = "Sound",
			sound = "fire_elemental_burn",
			parentNode = "head",
		},
	},
}

defineSound{
	name = "fire_elemental_walk",
	filename = {
		"assets/samples/monsters/fire_elemental_walk_01.wav",
		"assets/samples/monsters/fire_elemental_walk_02.wav",
	},
	loop = false,
	volume = 0.5,
	minDistance = 1,
	maxDistance = 10,
	clipDistance = 5,
}

defineSound{
	name = "fire_elemental_attack",
	filename = "assets/samples/monsters/fire_elemental_attack_01.wav",
	loop = false,
	volume = 1.0,
	minDistance = 2,
	maxDistance = 10,
	clipDistance = 5,
}

defineSound{
	name = "fire_elemental_hit",
	filename = "assets/samples/monsters/fire_elemental_hit_01.wav",
	loop = false,
	volume = 1,
	minDistance = 3,
	maxDistance = 10,
}

defineSound{
	name = "fire_elemental_die",
	filename = "assets/samples/monsters/fire_elemental_die_01.wav",
	loop = false,
	volume = 1,
	minDistance = 3,
	maxDistance = 10,
}

defineSound{
	name = "fire_elemental_burn",
	filename = "assets/samples/monsters/fire_elemental_burn_01.wav",
	loop = true,
	volume = 1,
	minDistance = 1,
	maxDistance = 14,
}

defineParticleSystem{
	name = "ash_elemental",
	emitters = {
		{
			emitterShape = "MeshShape",
			emissionRate = 25,
			emissionTime = 0,
			maxParticles = 25,
			sprayAngle = {0,360},
			velocity = {0.1*2,0.5*2},
			texture = "assets/textures/particles/smoke_01.tga",
			lifetime = {0.5,0.7},
			color = {0.15, 0.15, 0.15},
			opacity = 1,
			fadeIn = 0.1,
			fadeOut = 0.5,
			size = {0.5, 1.3},
			gravity = {0,2,0},
			airResistance = 0.05,
			rotationSpeed = 0.6,
			blendMode = "Translucent",
			depthBias = 0.1,
		},
		{
			-- flames
			emitterShape = "MeshShape",
			emissionRate = 500,
			emissionTime = 0,
			maxParticles = 500,
			sprayAngle = {0,30},
			velocity = {0.0, 0.0},
			texture = "assets/textures/particles/flame.tga",
			frameRate = 40,
			frameSize = 32,
			frameCount = 40,
			lifetime = {0.4, 0.7},
			colorAnimation = true,
			color0 = {0.00, 0.0, 0.00},
			color1 = {0.00, 0.0, 0.00},
			color2 = {0.00, 0.0, 0.00},
			color3 = {0.00, 0.0, 0.00},
			fadeIn = 0.01,
			fadeOut = 0.1,
			size = {0.021*2, 0.12*3},
			gravity = {0,3,0},
			airResistance = 1,
			rotationSpeed = 0,
			blendMode = "Additive",
			objectSpace = true,
		},

		{
			-- flames
			emitterShape = "MeshShape",
			emissionRate = 500,
			emissionTime = 0,
			maxParticles = 500,
			sprayAngle = {0,30},
			velocity = {0.0, 0.0},
			texture = "assets/textures/particles/flame.tga",
			frameRate = 40,
			frameSize = 32,
			frameCount = 40,
			lifetime = {0.1, 0.4},
			colorAnimation = true,
			color0 = {0.00, 0.0, 0.00},
			color1 = {0.00, 0.0, 0.00},
			color2 = {0.00, 0.0, 0.00},
			color3 = {0.00, 0.0, 0.00},
			fadeIn = 0.01,
			fadeOut = 0.1,
			size = {0.021*2, 0.12*3},
			gravity = {0,3,0},
			airResistance = 1,
			rotationSpeed = 0,
			blendMode = "Additive",
			objectSpace = false,
		},

		{
			-- small flames
			emitterShape = "MeshShape",
			maxParticles = 400,
			emissionRate = 500,
			emissionTime = 0,
			sprayAngle = {0,30},
			velocity = {0.0, 0.0},
			texture = "assets/textures/particles/flame.tga",
			frameRate = 40,
			frameSize = 32,
			frameCount = 40,
			lifetime = {0.2, 0.4},
			colorAnimation = true,
			color0 = {0.00, 0.0, 0.0},
			color1 = {0.01, 0.02, 0.01},
			color2 = {0.03, 0.03, 0.02},
			color3 = {0.05, 0.05, 0.05},
			fadeOut = 0.1,
			size = {0.021*2*0.5, 0.12*3*0.7},
			gravity = {0,4,0},
			airResistance = 1,
			rotationSpeed = 0,
			blendMode = "Additive",
		},

		-- sparkles
		{
			emitterShape = "MeshShape",
			emissionRate = 500,
			emissionTime = 0,
			maxParticles = 1000,
			sprayAngle = {0,360},
			velocity = {0.1,0.5},
			objectSpace = false,
			texture = "assets/textures/particles/darkness_cloud.tga",
			lifetime = {0.6,0.9},
			color0 = {0.1,0.1,0.1},
			opacity = 1,
			fadeIn = 0.1,
			fadeOut = 0.1,
			size = {0.03, 0.1},
			gravity = {0,0,0},
			airResistance = 0.01,
			rotationSpeed = 10,
			blendMode = "Translucent",
		},

		-- sparkles2
		{
			emitterShape = "MeshShape",
			emissionRate = 400,
			emissionTime = 0,
			maxParticles = 400,
			sprayAngle = {0,360},
			velocity = {0.1,0.5},
			objectSpace = false,
			texture = "assets/textures/particles/darkness_cloud.tga",
			lifetime = {1.5,2.0},
			color0 = {0.1,0.1,0.1},
			opacity = 1,
			fadeIn = 0.1,
			fadeOut = 0.1,
			size = {0.03, 0.1},
			gravity = {0,-2.5,0},
			airResistance = 0.01,
			rotationSpeed = 10,
			blendMode = "Translucent",
			clampToGroundPlane = true,
			depthBias = 0.1,
		},

		-- glow
		{
			spawnBurst = true,
			emissionRate = 1,
			emissionTime = 0,
			maxParticles = 1,
			boxMin = {0, 0.1, 0},
			boxMax = {0, 0.1, 0},
			sprayAngle = {0,30},
			velocity = {0,0},
			texture = "assets/textures/particles/glow.tga",
			lifetime = {1000000, 1000000},
			colorAnimation = false,
			color0 = {0.1, 0.1, 0.1},
			opacity = 0.04,
			fadeIn = 0.01,
			fadeOut = 0.5,
			size = {8, 8},
			gravity = {0,0,0},
			airResistance = 1,
			rotationSpeed = 0,
			blendMode = "Additive",
			objectSpace = true,
		},
	}
}
