-- This file has been generated by Dungeon Editor 2.2.4

-- TODO: place your custom sound definitions here
 defineSound{
	 name = "gen_fire_small",
	 filename = "mod_assets/fire_cave/sounds/gen_fire_small.wav",
	 loop = true,
	 volume = 0.8,
	 minDistance = 1,
	 maxDistance = 4,
 }
 
 defineSound{
	 name = "gen_lava",
	 filename = "mod_assets/fire_cave/sounds/gen_lava.wav",
	 loop = true,
	 volume = 0.8,
	 minDistance = 1,
	 maxDistance = 4,
 }
 
 defineSound{
	 name = "gen_lava_splash",
	 filename = "mod_assets/fire_cave/sounds/gen_lava_splash.wav",
	 loop = false,
	 volume = 1,
	 minDistance = 1,
	 maxDistance = 4,
 }
