defineParticleSystem{
	name = "amateria",
	emitters = {
		-- -- stars
		{
			emissionRate = 10,
            emissionTime = 0,
            emitterShape = "MeshShape",
			maxParticles = 40,
			sprayAngle = {0,30},
			velocity = {0.01,0.1},
			texture = "assets/textures/particles/teleporter.tga",
			lifetime = {12,12},
			color0 = {1.6,1.8,2.0},
			opacity = 0.5,
			fadeIn = 1.0,
			fadeOut = 1.0,
			size = {0.1, 0.2},
			gravity = {0,-0.01,0},
			airResistance = 0.3,
			rotationSpeed = 3,
            blendMode = "Additive",
            depthBias = 0.3,
            objectSpace = true,
            clampToGroundPlane = true,
		},

		-- small stars
		{
			emissionRate = 200,
            emissionTime = 0,
            emitterShape = "MeshShape",
			maxParticles = 600,
			sprayAngle = {0,30},
			velocity = {0.01,0.01},
			texture = "assets/textures/particles/teleporter.tga",
			lifetime = {5,5},
			color0 = {1.6,1.8,2.0},
			opacity = 0.75,
			fadeIn = 4.0,
			fadeOut = 0.5,
			size = {0.05, 0.1},
			gravity = {0,-0.01,0},
			airResistance = 0.5,
			rotationSpeed = 3,
            blendMode = "Additive",
            depthBias = 0.3,
			objectSpace = true,
        },
        
        -- fog
		{
			emitterShape = "MeshShape",
			emissionRate = 2,
			emissionTime = 0,
			maxParticles = 10,
			sprayAngle = {0,0},
			velocity = {0,0},
			texture = "assets/textures/particles/smoke_01.tga",
			lifetime = {1,5},
			color0 = {1, 1, 1},
			opacity = 0.4,
			fadeIn = 1,
			fadeOut = 4,
			size = {0.8, 1.0},
			gravity = {0,-0.2,0},
			airResistance = 0.5,
			rotationSpeed = 0.5,
            blendMode = "Additive",
            depthBias = 0.3,
			objectSpace = true,
		}
	}
}
