defineParticleSystem{
	name = "amateria",
	emitters = {
		-- -- stars
		{
			emissionRate = 10,
            emissionTime = 0,
            emitterShape = "MeshShape",
			maxParticles = 40,
			sprayAngle = {0,30},
			velocity = {0.01,0.1},
			texture = "assets/textures/particles/teleporter.tga",
			lifetime = {2,2},
			color0 = {1.6,1.8,2.0},
			opacity = 0.5,
			fadeIn = 1.0,
			fadeOut = 1.0,
			size = {0.1, 0.2},
			gravity = {0,-0.01,0},
			airResistance = 0.3,
			rotationSpeed = 3,
            blendMode = "Additive",
            depthBias = 0.3,
            objectSpace = true,
            clampToGroundPlane = true,
		},
        -- small stars burst
        {
            spawnBurst = true,
            emissionRate = 150,
            emissionTime = 0,
            emitterShape = "MeshShape",
            maxParticles = 150,
            sprayAngle = {0,30},
            velocity = {0.01,0.01},
            texture = "assets/textures/particles/teleporter.tga",
            lifetime = {2,3},
            color0 = {1.6,1.8,2.0},
            opacity = 0.75,
            fadeIn = 0.25,
            fadeOut = 0.5,
            size = {0.05, 0.1},
            gravity = {0,-0.01,0},
            airResistance = 0.5,
            rotationSpeed = 3,
            blendMode = "Additive",
            depthBias = 0.3,
            objectSpace = true,
        },
		-- small stars
		{
			emissionRate = 700,
            emissionTime = 0,
            emitterShape = "MeshShape",
			maxParticles = 1000,
			sprayAngle = {0,30},
			velocity = {0.01,0.01},
			texture = "assets/textures/particles/teleporter.tga",
			lifetime = {1,1},
			color0 = {1.6,1.8,2.0},
			opacity = 0.75,
			fadeIn = 0.25,
			fadeOut = 0.25,
			size = {0.05, 0.1},
			gravity = {0,-0.01,0},
			airResistance = 0.5,
			rotationSpeed = 3,
            blendMode = "Additive",
            depthBias = 0.3,
			objectSpace = true,
        },
        
        -- fog
		{
			emitterShape = "MeshShape",
			emissionRate = 2,
			emissionTime = 0,
			maxParticles = 10,
			sprayAngle = {0,0},
			velocity = {0,0},
			texture = "assets/textures/particles/smoke_01.tga",
			lifetime = {1,3},
			color0 = {1, 1, 1},
			opacity = 0.2,
			fadeIn = 1,
			fadeOut = 4,
			size = {0.8, 1.0},
			gravity = {0,-0.2,0},
			airResistance = 0.5,
			rotationSpeed = 0.5,
            blendMode = "Additive",
            depthBias = 0.3,
			objectSpace = true,
		}
	}
}

defineParticleSystem{
	name = "amateria_less",
	emitters = {
		-- -- stars
		{
			emissionRate = 10,
            emissionTime = 0,
            emitterShape = "MeshShape",
			maxParticles = 40,
			sprayAngle = {0,30},
			velocity = {0.01,0.05},
			texture = "assets/textures/particles/teleporter.tga",
			lifetime = {2,2},
			color0 = {1.6,1.8,2.0},
			opacity = 0.5,
			fadeIn = 1.0,
			fadeOut = 1.0,
			size = {0.05, 0.1},
			gravity = {0,-0.005,0},
			airResistance = 0.3,
			rotationSpeed = 3,
            blendMode = "Additive",
            depthBias = 0.3,
            objectSpace = true,
            clampToGroundPlane = true,
		},

		-- small stars
		{
			emissionRate = 300,
            emissionTime = 0,
            emitterShape = "MeshShape",
			maxParticles = 500,
			sprayAngle = {0,30},
			velocity = {0.01,0.01},
			texture = "assets/textures/particles/teleporter.tga",
			lifetime = {1,1},
			color0 = {1.6,1.8,2.0},
			opacity = 0.75,
			fadeIn = 0.25,
			fadeOut = 0.25,
			size = {0.003, 0.075},
			gravity = {0,-0.005,0},
			airResistance = 0.5,
			rotationSpeed = 3,
            blendMode = "Additive",
            depthBias = 0.3,
			objectSpace = true,
        },
        
        -- fog
		{
			emitterShape = "MeshShape",
			emissionRate = 2,
			emissionTime = 0,
			maxParticles = 10,
			sprayAngle = {0,0},
			velocity = {0,0},
			texture = "assets/textures/particles/smoke_01.tga",
			lifetime = {1,3},
			color0 = {1, 1, 1},
			opacity = 0.2,
			fadeIn = 1,
			fadeOut = 3,
			size = {0.5, 0.75},
			gravity = {0,-0.2,0},
			airResistance = 0.5,
			rotationSpeed = 0.5,
            blendMode = "Additive",
            depthBias = 0.3,
			objectSpace = true,
		}
	}
}
