defineObject{
	name = "soundGate",
	baseObject = "base_spell",
	components = {
		{
			class = "Particle",
			particleSystem = "soundGate",
			destroyObject = true,
		},
		{
			class = "Light",
			color = vec(0.4, 0.5, 0.6),
			brightness = 20,
			range = 5,
			fadeOut = 0.5,
		},
		{
			class = "Sound",
			sound = "balance",
		},
	},
}

defineParticleSystem{
	name = "soundGate",
	emitters = {
		-- glow
		{
			spawnBurst = true,
			emissionRate = 1,
			emissionTime = 0,
			maxParticles = 1,
			boxMin = {0, 1.1, 0},
			boxMax = {0, 1.1, 0},
			sprayAngle = {0, 0},
			velocity = {0,0},
			objectSpace = true,
			texture = "assets/textures/particles/glow.tga",
			lifetime = {0.4,0.4},
			color0 = {1.0, 1.0, 1.0},
			opacity = 0.7,
			fadeIn = 0.05,
			fadeOut = 0.2,
			size = {1.7, 1.7},
			gravity = {0,0,0},
			airResistance = 0.1,
			rotationSpeed = 0.3,
			blendMode = "Additive",
		},
		
		-- fog
		{
			spawnBurst = true,
			emissionRate = 10,
			emissionTime = 0,
			maxParticles = 10,
			boxMin = {-1.5, -3.0,-1.5},
			boxMax = { 1.5, 0.0, 1.5},
			sprayAngle = {0,360},
			velocity = {0.1,1},
			objectSpace = true,
			texture = "assets/textures/particles/fog.tga",
			lifetime = {1,1},
			color0 = {0.190294, 0.365000, 0.450490},
			opacity = 1,
			fadeIn = 0.5,
			fadeOut = 0.5,
			size = {2, 2},
			gravity = {0,0,0},
			airResistance = 0.1,
			rotationSpeed = 0.3,
			blendMode = "Additive",
		},

		-- stars
		{
			spawnBurst = true,
			emissionRate = 100,
			emissionTime = 0,
			maxParticles = 100,
			boxMin = {-1.5, 2.35, 0},
			boxMax = { 1.5, 0, 0},
			sprayAngle = {0,2},
			velocity = {0.1,0.2},
			objectSpace = true,
			texture = "assets/textures/particles/teleporter.tga",
			lifetime = {1.8,2},
			color0 = {1.8,1.8,1.8},
			opacity = 1,
			fadeIn = 0.1,
			fadeOut = 1.0,
			size = {0.1, 0.3},
			gravity = {0,-1,0},
			airResistance = 0.1,
			rotationSpeed = 2,
			blendMode = "Additive",
			clampToGroundPlane = true,
			depthBias = 0.1,
		},

		--small stars
		{
			spawnBurst = true,
			emissionRate = 60,
			emissionTime = 0,
			maxParticles = 100,
			boxMin = {-1.3, 2.35, 0},
			boxMax = {-1.4, 0, 0},
			sprayAngle = {0,1},
			velocity = {0.1,0.2},
			objectSpace = true,
			texture = "assets/textures/particles/teleporter.tga",
			lifetime = {1.8,2},
			color0 = {1.6,1.8,1.8},
			opacity = 1,
			fadeIn = 0.1,
			fadeOut = 1.0,
			size = {0.1, 0.3},
			gravity = {0,-1,0},
			airResistance = 0.1,
			rotationSpeed = 2,
			blendMode = "Additive",
			clampToGroundPlane = true,
			depthBias = 0.1,
		},
		--small stars
		{
			spawnBurst = true,
			emissionRate = 60,
			emissionTime = 0,
			maxParticles = 100,
			boxMin = {1.3, 2.35, 0},
			boxMax = {1.4, 0, 0},
			sprayAngle = {0,1},
			velocity = {0.1,0.2},
			objectSpace = true,
			texture = "assets/textures/particles/teleporter.tga",
			lifetime = {1.8,2},
			color0 = {1.6,1.8,1.8},
			opacity = 1,
			fadeIn = 0.1,
			fadeOut = 1.0,
			size = {0.1, 0.3},
			gravity = {0,-1,0},
			airResistance = 0.1,
			rotationSpeed = 2,
			blendMode = "Additive",
			clampToGroundPlane = true,
			depthBias = 0.1,
		},
		--small stars
		{
			spawnBurst = true,
			emissionRate = 60,
			emissionTime = 0,
			maxParticles = 100,
			boxMin = {-1.4, 2.35, 0},
			boxMax = {1.4, 2.35, 0},
			sprayAngle = {0,1},
			velocity = {0.1,0.2},
			objectSpace = true,
			texture = "assets/textures/particles/teleporter.tga",
			lifetime = {1.8,2},
			color0 = {1.6,1.8,1.8},
			opacity = 1,
			fadeIn = 0.1,
			fadeOut = 1.0,
			size = {0.1, 0.3},
			gravity = {0,-1,0},
			airResistance = 0.1,
			rotationSpeed = 2,
			blendMode = "Additive",
			clampToGroundPlane = true,
			depthBias = 0.1,
		},
		--small stars
		{
			spawnBurst = true,
			emissionRate = 60,
			emissionTime = 0,
			maxParticles = 100,
			boxMin = {-1.4, 0.05, 0},
			boxMax = {1.4, 0.05, 0},
			sprayAngle = {0,1},
			velocity = {0.1,0.2},
			objectSpace = true,
			texture = "assets/textures/particles/teleporter.tga",
			lifetime = {1.8,2},
			color0 = {1.6,1.8,1.8},
			opacity = 1,
			fadeIn = 0.1,
			fadeOut = 1.0,
			size = {0.1, 0.3},
			gravity = {0,-1,0},
			airResistance = 0.1,
			rotationSpeed = 2,
			blendMode = "Additive",
			clampToGroundPlane = true,
			depthBias = 0.1,
		}
	}
}
